import type { EngineRequest, EngineResponse, BuildStats } from "./types";

let factory: import("wasmoon").default | null = null;
let lua: Awaited<ReturnType<import("wasmoon").default["createEngine"]>> | null = null;
let initialized = false;

function reply(msg: EngineResponse): void {
  postMessage(msg);
}

function progress(id: number, stage: string): void {
  reply({ id, type: "progress", stage });
}

const LUA_SHIMS = `
  -- Rendering stubs (PoB desktop rendering API)
  function SetDrawLayer(l, s) end
  function SetDrawColor(r, g, b, a) end
  function DrawImage(h, x, y, w, hh, ...) end
  function DrawImageQuad(h, ...) end
  function DrawString(x, y, a, h, f, t) end
  function DrawStringWidth(h, f, t) return 0 end
  function DrawStringCursorIndex(h, f, t, cx, cy) return 0 end
  function NewImageHandle() return { Load = function() end, SetLoadingPriority = function() end, ImageSize = function() return 0, 0 end } end
  function StripEscapes(t) return t end
  function GetScreenSize() return 1920, 1080 end
  function SetCursorPos(x, y) end
  function GetCursorPos() return 0, 0 end
  function ShowCursor(s) end
  function IsKeyDown(k) return false end
  function Copy(t) end
  function Paste() return "" end
  function GetTime() return 0 end
  function SetWindowTitle(t) end

  -- Filesystem stubs
  function GetScriptPath() return "/pob" end
  function GetRuntimePath() return "/pobrt" end
  function GetUserPath() return "/user" end
  function MakeDir(p) end
  function RemoveDir(p) end
  function SetWorkDir(p) end
  function GetWorkDir() return "" end

  -- Subprocess stubs
  function LaunchSubScript(...) end
  function AbortSubScript(id) end
  function IsSubScriptRunning(id) return false end

  -- System stubs
  function SpawnProcess(c, a) end
  function OpenURL(u) end
  function SetProfiling(e) end
  function Restart() end
  function Exit() end
  function TakeScreenshot() end
  function GetCloudProvider(p) return nil, nil, nil end

  -- File search stubs
  function NewFileSearch(path, findDirectories)
    return nil
  end

  -- Inflate/Deflate stubs
  Inflate = function(d) return "" end
  Deflate = function(d) return "" end

  -- Module loading
  function LoadModule(fn, ...)
    if not fn:match("%.lua") then fn = fn .. ".lua" end
    local f, e = loadfile(fn)
    if f then return f(...) else error("LoadModule() error loading '"..fn.."': "..tostring(e)) end
  end

  function PLoadModule(fn, ...)
    if not fn:match("%.lua") then fn = fn .. ".lua" end
    local f, e = loadfile(fn)
    if f then return PCall(f, ...) else error("PLoadModule() error loading '"..fn.."': "..tostring(e)) end
  end

  function PCall(fn, ...)
    local r = {pcall(fn, ...)}
    if r[1] then table.remove(r, 1); return nil, unpack(r) else return r[2] end
  end

  function ConPrintf(fmt, ...)
    -- silent in browser
  end
  function ConPrintTable(t, n) end
  function ConExecute(c) end
  function ConClear() end

  -- Override require for missing modules
  local _orig_require = require
  function require(name)
    if name == "lcurl.safe" then return nil end
    return _orig_require(name)
  end

  -- PoB-specific stubs
  mainObject = nil
  function SetMainObject(obj) mainObject = obj end
  function GetMainObject() return mainObject end

  -- Callback system (from PoB's runtime)
  local callbacks = {}
  function SetCallback(name) callbacks[name] = true end
  function runCallback(name, ...)
    if mainObject and mainObject[name] then
      return mainObject[name](mainObject, ...)
    end
  end

  -- JIT stub (wasmoon uses PUC Lua, not LuaJIT)
  jit = { opt = { start = function() end }, version = "disabled" }

  -- I/O stubs for PoB file operations
  local _orig_io_open = io.open
  io.open = function(path, mode)
    if mode and mode:match("w") then return nil, "read-only" end
    return _orig_io_open(path, mode)
  end
`;

async function fetchAndMountFiles(
  f: import("wasmoon").default,
  baseUrl: string
): Promise<number> {
  // Fetch the file manifest (generated by gen-manifest.sh)
  const listResp = await fetch(`${baseUrl}/file-list.json`);
  if (!listResp.ok) throw new Error(`Failed to fetch file list: ${listResp.status}`);
  const files: string[] = await listResp.json();

  let mounted = 0;
  const batchSize = 20;

  // Mount files in parallel batches to speed up loading
  for (let i = 0; i < files.length; i += batchSize) {
    const batch = files.slice(i, i + batchSize);
    const results = await Promise.allSettled(
      batch.map(async (file) => {
        const resp = await fetch(`${baseUrl}/${file}`);
        if (!resp.ok) return null;
        const content = await resp.text();
        return { file, content };
      })
    );

    for (const result of results) {
      if (result.status === "fulfilled" && result.value) {
        const { file, content } = result.value;
        await f.mountFile(`/pob/${file}`, content);
        mounted++;
      }
    }
  }

  // Also mount runtime support files
  const runtimeFiles = [
    "runtime/xml.lua",
    "runtime/base64.lua",
    "runtime/dkjson.lua",
    "runtime/sha1/init.lua",
    "runtime/sha1/common.lua",
    "runtime/sha1/pure_lua_ops.lua",
    "runtime/sha1/lua53_ops.lua",
    "runtime/sha1/bit32_ops.lua",
    "runtime/sha1/bit_ops.lua",
    "runtime/sha2.lua",
    "runtime/socket.lua",
  ];

  for (const file of runtimeFiles) {
    try {
      const resp = await fetch(`${baseUrl}/${file}`);
      if (!resp.ok) continue;
      const content = await resp.text();
      const mountPath = file.replace("runtime/", "/pobrt/");
      await f.mountFile(mountPath, content);
      mounted++;
    } catch {
      // skip optional runtime files
    }
  }

  return mounted;
}

async function handleInit(id: number, _gameId: string): Promise<void> {
  try {
    progress(id, "Loading wasmoon...");
    const wasmoon = await import("wasmoon");
    const LuaFactory = wasmoon.LuaFactory;

    progress(id, "Creating Lua VM...");
    factory = new LuaFactory();
    lua = await factory.createEngine({
      openStandardLibs: true,
      injectObjects: true,
    });

    progress(id, "Injecting HeadlessWrapper shims...");
    await lua.doString(LUA_SHIMS);

    progress(id, "Mounting PoB files...");
    const mounted = await fetchAndMountFiles(factory, "/data/pob");
    progress(id, `Mounted ${mounted} files`);

    // Set up Lua package path so require/loadfile finds PoB files
    await lua.doString(`
      package.path = "/pob/?.lua;/pob/?/init.lua;/pobrt/?.lua;/pobrt/?/init.lua;" .. package.path
    `);

    // Test Lua works
    await lua.doString('_tsc_ready = true');
    const ready = lua.global.get("_tsc_ready");
    if (!ready) throw new Error("Lua VM failed self-test");

    // Try to boot Launch.lua (may fail if not all files are mounted)
    try {
      progress(id, "Booting Launch.lua...");
      await lua.doString(`
        local ok, err = pcall(dofile, "/pob/Launch.lua")
        if not ok then
          _tsc_launch_error = tostring(err)
        else
          _tsc_launch_ok = true
        end
      `);
      const launchOk = lua.global.get("_tsc_launch_ok");
      const launchErr = lua.global.get("_tsc_launch_error");
      if (launchOk) {
        progress(id, "Launch.lua loaded");
      } else {
        progress(id, `Launch.lua partial: ${String(launchErr).substring(0, 100)}`);
      }
    } catch (e) {
      progress(id, `Launch.lua skipped: ${e instanceof Error ? e.message.substring(0, 80) : "unknown"}`);
    }

    initialized = true;
    reply({ id, type: "ready" });
  } catch (e) {
    reply({
      id,
      type: "error",
      message: `Init failed: ${e instanceof Error ? e.message : String(e)}`,
    });
  }
}

async function handleEvaluate(id: number, xml: string): Promise<void> {
  if (!initialized || !lua) {
    reply({ id, type: "error", message: "Engine not initialized" });
    return;
  }

  try {
    progress(id, "Evaluating build...");

    // Try to use the PoB engine if Launch.lua loaded
    const launchOk = lua.global.get("_tsc_launch_ok");

    const stats: BuildStats = {
      total_dps: 0,
      combined_dps: 0,
      total_ehp: 0,
      life: 60,
      energy_shield: 0,
      mana: 50,
      strength: 20,
      dexterity: 20,
      intelligence: 20,
      armour: 0,
      evasion: 16,
      evade_chance: 0,
      block_chance: 0,
      spell_block: 0,
      suppression: 0,
      phys_reduction: 0,
      fire_res: -60,
      cold_res: -60,
      lightning_res: -60,
      chaos_res: -60,
      fire_res_max: 75,
      cold_res_max: 75,
      lightning_res_max: 75,
      chaos_res_max: 75,
      life_regen: 0,
      mana_regen: 0.9,
      crit_chance: 0,
      crit_multiplier: 150,
      attack_speed: 1.2,
      hit_chance: 5,
      accuracy: 40,
      class_name: "Scion",
      ascendancy: "",
      level: 1,
      allocated_nodes: [],
      main_socket_group: 0,
    };

    if (launchOk) {
      try {
        // Set the XML in Lua and try to load the build
        lua.global.set("_tsc_build_xml", xml);
        await lua.doString(`
          local ok, err = pcall(function()
            loadBuildFromXML(_tsc_build_xml, "imported")
          end)
          if ok then
            _tsc_eval_ok = true
          else
            _tsc_eval_error = tostring(err)
          end
        `);

        const evalOk = lua.global.get("_tsc_eval_ok");
        if (evalOk) {
          // Extract stats from the loaded build
          await lua.doString(`
            local build = mainObject and mainObject.main and mainObject.main.modes and mainObject.main.modes["BUILD"]
            if build and build.calcsTab and build.calcsTab.mainOutput then
              local out = build.calcsTab.mainOutput
              _tsc_stats = {
                total_dps = out.TotalDPS or 0,
                combined_dps = out.CombinedDPS or out.TotalDPS or 0,
                life = out.Life or 60,
                energy_shield = out.EnergyShield or 0,
                mana = out.Mana or 50,
                strength = out.Str or 20,
                dexterity = out.Dex or 20,
                intelligence = out.Int or 20,
                armour = out.Armour or 0,
                evasion = out.Evasion or 16,
                fire_res = out.FireResist or -60,
                cold_res = out.ColdResist or -60,
                lightning_res = out.LightningResist or -60,
                chaos_res = out.ChaosResist or -60,
                crit_chance = out.CritChance or 0,
                crit_multiplier = out.CritMultiplier or 150,
                attack_speed = out.Speed or 1.2,
                hit_chance = out.HitChance or 5,
                level = build.characterLevel or 1,
                class_name = build.className or "Scion",
                ascendancy = build.ascendClassName or "",
              }
            end
          `);

          const luaStats = lua.global.get("_tsc_stats");
          if (luaStats && typeof luaStats === "object") {
            Object.assign(stats, luaStats);
          }
        }
      } catch (e) {
        console.warn("PoB eval failed, using defaults:", e);
      }
    }

    reply({
      id,
      type: "evaluated",
      stats,
      items: [],
      skills: [],
    });
  } catch (e) {
    reply({
      id,
      type: "error",
      message: `Evaluate failed: ${e instanceof Error ? e.message : String(e)}`,
    });
  }
}

self.onmessage = async (e: MessageEvent<EngineRequest>) => {
  const msg = e.data;

  switch (msg.type) {
    case "init":
      await handleInit(msg.id, msg.gameId);
      break;
    case "evaluate":
      await handleEvaluate(msg.id, msg.xml);
      break;
    case "ping":
      reply({ id: msg.id, type: "pong" });
      break;
    default: {
      const unknown = msg as { id: number; type: string };
      reply({
        id: unknown.id,
        type: "error",
        message: `Unknown message type: ${unknown.type}`,
      });
    }
  }
};
