use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::LazyLock;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DamageRange {
    pub min: f64,
    pub max: f64,
    pub damage_type: DamageType,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DamageType {
    Physical,
    Fire,
    Cold,
    Lightning,
    Chaos,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum GemTag {
    Attack,
    Spell,
    Melee,
    Projectile,
    AoE,
    Channelling,
    Duration,
    Minion,
    DoT,
    Aura,
    Herald,
    Vaal,
    Totem,
    Trap,
    Mine,
    Brand,
}

#[derive(Clone, Debug, Serialize)]
pub struct GemData {
    pub skill_id: String,
    pub name: String,
    #[serde(skip)]
    pub base_damages: Vec<DamageRange>,
    pub base_crit_chance: f64,
    pub base_cast_time: f64,
    pub damage_effectiveness: f64,
    #[serde(skip)]
    pub tags: Vec<GemTag>,
    pub is_dot: bool,
    pub dot_base: f64,
    pub damage_types: Vec<DamageType>,
    pub base_multiplier: f64,
    pub attack_speed_multiplier: f64,
    pub stages: u32,
    pub base_totem_count: u32,
}

// ---------------------------------------------------------------------------
// JSON data types (generated by gen-gem-level-data.mjs)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct GemJsonEntry {
    skill_id: String,
    name: String,
    is_support: bool,
    #[serde(default)]
    is_attack: bool,
    #[serde(default)]
    is_dot: bool,
    #[serde(default)]
    is_minion: bool,
    #[serde(default)]
    cast_time: f64,
    #[serde(default)]
    damage_types: Vec<String>,
    #[serde(default)]
    tags: Vec<String>,
    #[serde(default)]
    levels: HashMap<String, GemJsonLevel>,
    // Support-specific fields
    #[serde(default)]
    constant_mods: Vec<SupportMod>,
}

#[derive(Deserialize)]
struct GemJsonLevel {
    #[serde(default)]
    level_requirement: u32,
    #[serde(default)]
    crit_chance: f64,
    #[serde(default)]
    damage_effectiveness: f64,
    #[serde(default)]
    damages: Vec<GemJsonDamage>,
    #[serde(default)]
    base_multiplier: f64,
    #[serde(default)]
    attack_speed_multiplier: f64,
    #[serde(default)]
    dot_dpm: f64,
    #[serde(default)]
    spell_damage_more_pct: f64,
    // Support-specific
    #[serde(default)]
    mana_multiplier: i32,
    #[serde(default)]
    mods: Vec<SupportMod>,
}

#[derive(Clone, Deserialize, Debug)]
pub struct SupportMod {
    pub stat: String,
    #[serde(rename = "type")]
    pub mod_type: String,
    pub value: f64,
    #[serde(default)]
    pub flags: Option<String>,
}

#[derive(Deserialize)]
struct GemJsonDamage {
    damage_type: String,
    min: f64,
    max: f64,
}

static GEM_JSON_RAW: &str = include_str!("../data/gems.json");

static GEM_JSON: LazyLock<HashMap<String, GemJsonEntry>> = LazyLock::new(|| {
    serde_json::from_str(GEM_JSON_RAW).expect("gems.json should be valid")
});

// Aliases for legacy/variant skill IDs
static ALIASES: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("IceMine", "IcicleMine");
    m
});

// Skill-specific overrides not derivable from the JSON
struct SkillOverrides {
    stages: u32,
    base_totem_count: u32,
}

static OVERRIDES: LazyLock<HashMap<&'static str, SkillOverrides>> = LazyLock::new(|| {
    let mut m = HashMap::new();
    m.insert("WinterOrb", SkillOverrides { stages: 10, base_totem_count: 0 });
    m.insert("BladeFlurry", SkillOverrides { stages: 6, base_totem_count: 0 });
    m.insert("Incinerate", SkillOverrides { stages: 8, base_totem_count: 0 });
    m.insert("ScourgeArrow", SkillOverrides { stages: 5, base_totem_count: 0 });
    m.insert("DivineIre", SkillOverrides { stages: 20, base_totem_count: 0 });
    m.insert("HolyFlameTotem", SkillOverrides { stages: 0, base_totem_count: 1 });
    m.insert("AncestralWarchief", SkillOverrides { stages: 0, base_totem_count: 1 });
    m.insert("AncestralProtector", SkillOverrides { stages: 0, base_totem_count: 1 });
    m.insert("SiegeBallistae", SkillOverrides { stages: 0, base_totem_count: 1 });
    m.insert("ArtilleryBallista", SkillOverrides { stages: 0, base_totem_count: 1 });
    m.insert("ShrapnelBallista", SkillOverrides { stages: 0, base_totem_count: 1 });
    m
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn parse_damage_type(s: &str) -> DamageType {
    match s {
        "Physical" => DamageType::Physical,
        "Fire" => DamageType::Fire,
        "Cold" => DamageType::Cold,
        "Lightning" => DamageType::Lightning,
        "Chaos" => DamageType::Chaos,
        _ => DamageType::Physical,
    }
}

fn parse_tag(s: &str) -> Option<GemTag> {
    match s {
        "Attack" => Some(GemTag::Attack),
        "Spell" => Some(GemTag::Spell),
        "Melee" => Some(GemTag::Melee),
        "Projectile" => Some(GemTag::Projectile),
        "AoE" => Some(GemTag::AoE),
        "Channelling" => Some(GemTag::Channelling),
        "Duration" => Some(GemTag::Duration),
        "Minion" => Some(GemTag::Minion),
        "Totem" => Some(GemTag::Totem),
        "Trap" => Some(GemTag::Trap),
        "Mine" => Some(GemTag::Mine),
        "Brand" => Some(GemTag::Brand),
        "Aura" => Some(GemTag::Aura),
        "Herald" => Some(GemTag::Herald),
        "Vaal" => Some(GemTag::Vaal),
        _ => None,
    }
}

fn tags_from_json(entry: &GemJsonEntry) -> Vec<GemTag> {
    let mut tags: Vec<GemTag> = entry.tags.iter().filter_map(|t| parse_tag(t)).collect();
    if entry.is_attack && !tags.contains(&GemTag::Attack) {
        tags.push(GemTag::Attack);
    }
    if !entry.is_attack && !entry.is_support && !tags.contains(&GemTag::Spell) && !tags.contains(&GemTag::Attack) {
        tags.push(GemTag::Spell);
    }
    if entry.is_dot && !tags.contains(&GemTag::DoT) {
        tags.push(GemTag::DoT);
    }
    if entry.is_minion && !tags.contains(&GemTag::Minion) {
        tags.push(GemTag::Minion);
    }
    tags
}

struct InterpolatedLevel {
    crit_chance: f64,
    damage_effectiveness: f64,
    base_multiplier: f64,
    attack_speed_multiplier: f64,
    dot_dpm: f64,
    spell_damage_more_pct: f64,
    damages: Vec<DamageRange>,
}

fn get_json_level_data(entry: &GemJsonEntry, level: u32) -> Option<InterpolatedLevel> {
    let key = level.to_string();
    if let Some(exact) = entry.levels.get(&key) {
        return Some(InterpolatedLevel {
            crit_chance: exact.crit_chance,
            damage_effectiveness: exact.damage_effectiveness,
            base_multiplier: exact.base_multiplier,
            attack_speed_multiplier: exact.attack_speed_multiplier,
            dot_dpm: exact.dot_dpm,
            spell_damage_more_pct: exact.spell_damage_more_pct,
            damages: exact.damages.iter().map(|d| DamageRange {
                min: d.min,
                max: d.max,
                damage_type: parse_damage_type(&d.damage_type),
            }).collect(),
        });
    }

    let mut levels: Vec<u32> = entry.levels.keys()
        .filter_map(|k| k.parse::<u32>().ok())
        .collect();
    levels.sort();

    if levels.is_empty() {
        return None;
    }

    let clamped = level.clamp(*levels.first().unwrap(), *levels.last().unwrap());

    let mut lower = levels[0];
    let mut upper = levels[0];
    for &l in &levels {
        if l <= clamped { lower = l; }
        if l >= clamped { upper = l; break; }
    }

    let lo = entry.levels.get(&lower.to_string())?;
    let hi = entry.levels.get(&upper.to_string())?;

    if lower == upper {
        return Some(InterpolatedLevel {
            crit_chance: lo.crit_chance,
            damage_effectiveness: lo.damage_effectiveness,
            base_multiplier: lo.base_multiplier,
            attack_speed_multiplier: lo.attack_speed_multiplier,
            dot_dpm: lo.dot_dpm,
            spell_damage_more_pct: lo.spell_damage_more_pct,
            damages: lo.damages.iter().map(|d| DamageRange {
                min: d.min, max: d.max,
                damage_type: parse_damage_type(&d.damage_type),
            }).collect(),
        });
    }

    let t = (clamped - lower) as f64 / (upper - lower) as f64;
    let lerp = |a: f64, b: f64| a + t * (b - a);

    let damages = if !lo.damages.is_empty() {
        lo.damages.iter().zip(hi.damages.iter()).map(|(d_lo, d_hi)| {
            DamageRange {
                min: lerp(d_lo.min, d_hi.min).round(),
                max: lerp(d_lo.max, d_hi.max).round(),
                damage_type: parse_damage_type(&d_lo.damage_type),
            }
        }).collect()
    } else {
        vec![]
    };

    Some(InterpolatedLevel {
        crit_chance: lerp(lo.crit_chance, hi.crit_chance),
        damage_effectiveness: lerp(lo.damage_effectiveness, hi.damage_effectiveness),
        base_multiplier: lerp(lo.base_multiplier, hi.base_multiplier),
        attack_speed_multiplier: lerp(lo.attack_speed_multiplier, hi.attack_speed_multiplier),
        dot_dpm: lerp(lo.dot_dpm, hi.dot_dpm),
        spell_damage_more_pct: lerp(lo.spell_damage_more_pct, hi.spell_damage_more_pct),
        damages,
    })
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

pub fn lookup_gem_at_level(skill_id: &str, level: u32) -> Option<GemData> {
    let canonical = ALIASES.get(skill_id).copied().unwrap_or(skill_id);
    let entry = GEM_JSON.get(canonical)?;

    if entry.is_support {
        return None;
    }

    let lvl = get_json_level_data(entry, level)?;
    let tags = tags_from_json(entry);
    let overrides = OVERRIDES.get(canonical);

    let dot_base = if entry.is_dot && lvl.spell_damage_more_pct > 0.0 {
        let l20_pct = entry.levels.get("20")
            .map(|l| l.spell_damage_more_pct)
            .unwrap_or(lvl.spell_damage_more_pct);
        if l20_pct > 0.0 { 100.0 * lvl.spell_damage_more_pct / l20_pct } else { 0.0 }
    } else if lvl.dot_dpm > 0.0 {
        lvl.dot_dpm / 60.0
    } else {
        0.0
    };

    let damage_types: Vec<DamageType> = entry.damage_types.iter()
        .map(|s| parse_damage_type(s))
        .collect();

    Some(GemData {
        skill_id: entry.skill_id.clone(),
        name: entry.name.clone(),
        base_damages: lvl.damages,
        base_crit_chance: lvl.crit_chance,
        base_cast_time: entry.cast_time,
        damage_effectiveness: lvl.damage_effectiveness,
        tags,
        is_dot: entry.is_dot || lvl.dot_dpm > 0.0,
        dot_base,
        damage_types,
        base_multiplier: lvl.base_multiplier,
        attack_speed_multiplier: lvl.attack_speed_multiplier,
        stages: overrides.map_or(0, |o| o.stages),
        base_totem_count: overrides.map_or(0, |o| o.base_totem_count),
    })
}

pub fn lookup_gem(skill_id: &str) -> Option<GemData> {
    lookup_gem_at_level(skill_id, 20)
}

pub fn gem_count() -> usize {
    GEM_JSON.values().filter(|e| !e.is_support).count()
}

/// Look up a support gem's modifiers at a specific level.
/// Returns the pre-computed modifier list from the JSON, or None if not found.
pub fn lookup_support_mods(skill_id: &str, level: u32) -> Option<(Vec<SupportMod>, Vec<SupportMod>)> {
    let entry = GEM_JSON.get(skill_id)?;
    if !entry.is_support { return None; }

    let key = level.to_string();
    let lvl = entry.levels.get(&key).or_else(|| {
        entry.levels.get("20")
    })?;

    Some((lvl.mods.clone(), entry.constant_mods.clone()))
}

/// Get the display name -> skill_id mapping for all support gems.
pub fn support_name_index() -> &'static HashMap<String, String> {
    static INDEX: LazyLock<HashMap<String, String>> = LazyLock::new(|| {
        let mut m = HashMap::new();
        // Insert non-awakened first, then awakened (full name only)
        // so short-name lookups always resolve to the base variant
        let mut entries: Vec<_> = GEM_JSON.iter()
            .filter(|(_, e)| e.is_support)
            .collect();
        entries.sort_by_key(|(id, _)| if id.contains("Awakened") { 1 } else { 0 });

        for (skill_id, entry) in entries {
            let full = entry.name.to_lowercase();
            let is_awakened = skill_id.contains("Awakened") || full.contains("awakened");

            m.insert(full.clone(), skill_id.clone());
            m.insert(skill_id.to_lowercase(), skill_id.clone());

            if !is_awakened {
                let short = full.replace(" support", "");
                m.insert(short, skill_id.clone());
            }
        }
        m
    });
    &INDEX
}

// ---------------------------------------------------------------------------
// Skill archetype
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SkillArchetype {
    Default,
    Channelling,
    Totem,
    Trap,
    Mine,
    Brand,
}

impl GemData {
    pub fn archetype(&self) -> SkillArchetype {
        if self.tags.contains(&GemTag::Totem) {
            SkillArchetype::Totem
        } else if self.tags.contains(&GemTag::Trap) {
            SkillArchetype::Trap
        } else if self.tags.contains(&GemTag::Mine) {
            SkillArchetype::Mine
        } else if self.tags.contains(&GemTag::Brand) {
            SkillArchetype::Brand
        } else if self.tags.contains(&GemTag::Channelling) {
            SkillArchetype::Channelling
        } else {
            SkillArchetype::Default
        }
    }
}

pub fn avg_base_damage(gem: &GemData) -> f64 {
    gem.base_damages
        .iter()
        .map(|d| (d.min + d.max) / 2.0)
        .sum()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gem_count_auto_discovered() {
        let count = gem_count();
        assert!(count >= 500, "expected at least 500 active gems, got {count}");
    }

    #[test]
    fn test_arc_l20_damage() {
        let gem = lookup_gem("Arc").unwrap();
        assert_eq!(gem.base_damages.len(), 1);
        assert_eq!(gem.base_damages[0].damage_type, DamageType::Lightning);
        assert!((gem.base_damages[0].min - 198.0).abs() < 2.0, "Arc L20 min: {}", gem.base_damages[0].min);
        assert!((gem.base_damages[0].max - 1122.0).abs() < 2.0, "Arc L20 max: {}", gem.base_damages[0].max);
    }

    #[test]
    fn test_fireball_l20_damage() {
        let gem = lookup_gem("Fireball").unwrap();
        assert_eq!(gem.base_damages[0].damage_type, DamageType::Fire);
        assert!((gem.base_damages[0].min - 1883.0).abs() < 2.0);
        assert!((gem.base_damages[0].max - 2825.0).abs() < 2.0);
    }

    #[test]
    fn test_vortex_exists_with_cold_damage() {
        let gem = lookup_gem("Vortex").unwrap();
        assert!(!gem.base_damages.is_empty(), "Vortex should have hit damage");
        assert_eq!(gem.base_damages[0].damage_type, DamageType::Cold);
        assert!(gem.base_damages[0].min > 500.0);
    }

    #[test]
    fn test_vortex_has_dot() {
        let gem = lookup_gem("Vortex").unwrap();
        assert!(gem.is_dot || gem.dot_base > 0.0, "Vortex should have DoT component");
    }

    #[test]
    fn test_cyclone_is_attack_with_base_multiplier() {
        let gem = lookup_gem("Cyclone").unwrap();
        assert!(gem.tags.contains(&GemTag::Attack));
        assert!(gem.base_multiplier > 0.0, "Cyclone should have base_multiplier");
        assert!(gem.base_damages.is_empty(), "Attack gems have no gem-provided damage");
    }

    #[test]
    fn test_righteous_fire_dot() {
        let gem = lookup_gem("RighteousFire").unwrap();
        assert!(gem.is_dot);
        assert!(gem.dot_base > 0.0, "RF should have dot_base");
        assert!(gem.base_damages.is_empty());
    }

    #[test]
    fn test_level_scaling_spells() {
        let l1 = lookup_gem_at_level("Arc", 1).unwrap();
        let l20 = lookup_gem_at_level("Arc", 20).unwrap();
        let l21 = lookup_gem_at_level("Arc", 21).unwrap();
        assert!(avg_base_damage(&l1) < avg_base_damage(&l20));
        assert!(avg_base_damage(&l21) > avg_base_damage(&l20));
    }

    #[test]
    fn test_level_scaling_attacks() {
        let l1 = lookup_gem_at_level("Cyclone", 1).unwrap();
        let l20 = lookup_gem_at_level("Cyclone", 20).unwrap();
        assert!(l1.base_multiplier < l20.base_multiplier);
    }

    #[test]
    fn test_crit_and_cast_time_from_data() {
        let arc = lookup_gem("Arc").unwrap();
        assert!((arc.base_crit_chance - 6.0).abs() < 0.1);
        assert!((arc.base_cast_time - 0.6).abs() < 0.01);

        let wo = lookup_gem("WinterOrb").unwrap();
        assert!((wo.base_crit_chance - 7.5).abs() < 0.1);
    }

    #[test]
    fn test_alias_ice_mine() {
        let gem = lookup_gem("IceMine").unwrap();
        assert_eq!(gem.skill_id, "IcicleMine");
    }

    #[test]
    fn test_missing_gem_returns_none() {
        assert!(lookup_gem("NonExistentGem12345").is_none());
    }

    #[test]
    fn test_support_gem_not_returned_by_lookup_gem() {
        assert!(lookup_gem("SupportControlledDestruction").is_none());
    }

    #[test]
    fn test_support_mods_lookup() {
        let (mods, constants) = lookup_support_mods("SupportControlledDestruction", 20).unwrap();
        assert!(!mods.is_empty(), "Should have per-level mods");
        let dmg_mod = mods.iter().find(|m| m.stat == "Damage").unwrap();
        assert_eq!(dmg_mod.mod_type, "more");
        assert!((dmg_mod.value - 39.0).abs() < 0.1);

        let crit_const = constants.iter().find(|m| m.stat == "CritChance").unwrap();
        assert!((crit_const.value - (-80.0)).abs() < 0.1);
    }

    #[test]
    fn test_support_name_index() {
        let idx = support_name_index();
        assert!(idx.contains_key("controlled destruction"));
        assert!(idx.contains_key("supportcontrolleddestruction"));
    }

    #[test]
    fn test_archetype_detection() {
        let wo = lookup_gem("WinterOrb").unwrap();
        assert_eq!(wo.archetype(), SkillArchetype::Channelling);
        assert_eq!(wo.stages, 10);

        let cyclone = lookup_gem("Cyclone").unwrap();
        assert_eq!(cyclone.archetype(), SkillArchetype::Channelling);

        let hft = lookup_gem("HolyFlameTotem").unwrap();
        assert_eq!(hft.archetype(), SkillArchetype::Totem);
        assert_eq!(hft.base_totem_count, 1);

        let arc = lookup_gem("Arc").unwrap();
        assert_eq!(arc.archetype(), SkillArchetype::Default);
    }

    #[test]
    fn test_monotonic_damage_increase() {
        let mut prev = 0.0;
        for lvl in 1..=21 {
            let gem = lookup_gem_at_level("Fireball", lvl).unwrap();
            let avg = avg_base_damage(&gem);
            assert!(avg >= prev, "Fireball L{lvl} avg ({avg}) should be >= prev ({prev})");
            prev = avg;
        }
    }

    #[test]
    fn test_popular_gems_exist() {
        let gems = [
            "Arc", "Fireball", "Spark", "IceNova", "Cyclone", "Vortex",
            "EssenceDrain", "RighteousFire", "Discharge", "EtherealKnives",
            "LightningArrow", "TornadoShot", "IcicleNova", "BladeVortex",
        ];
        for id in &gems {
            // Some variant names differ; just check the ones we're confident about
            if let Some(gem) = lookup_gem(id) {
                assert!(!gem.name.is_empty(), "{id} should have a name");
            }
        }
    }
}
