/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ApiBuildsRouteImport } from './routes/api/builds'
import { Route as ApiCharacterRouteImport } from './routes/api/character'
import { Route as ApiImportRouteImport } from './routes/api/import'
import { Route as ApiNinjaRouteImport } from './routes/api/ninja'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiTradeRouteImport } from './routes/api/trade'
import { Route as BuildIdRouteImport } from './routes/build.$id'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiBuildsLeaderboardRouteImport } from './routes/api/builds/leaderboard'
import { Route as ApiBuildsSharedRouteImport } from './routes/api/builds/shared'
import { Route as ApiBuildsIdShareRouteImport } from './routes/api/builds/$id.share'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildsRoute = ApiBuildsRouteImport.update({
  id: '/api/builds',
  path: '/api/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharacterRoute = ApiCharacterRouteImport.update({
  id: '/api/character',
  path: '/api/character',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNinjaRoute = ApiNinjaRouteImport.update({
  id: '/api/ninja',
  path: '/api/ninja',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradeRoute = ApiTradeRouteImport.update({
  id: '/api/trade',
  path: '/api/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIdRoute = BuildIdRouteImport.update({
  id: '/build/$id',
  path: '/build/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildsLeaderboardRoute = ApiBuildsLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ApiBuildsRoute,
} as any)
const ApiBuildsSharedRoute = ApiBuildsSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => ApiBuildsRoute,
} as any)
const ApiBuildsIdShareRoute = ApiBuildsIdShareRouteImport.update({
  id: '/$id/share',
  path: '/$id/share',
  getParentRoute: () => ApiBuildsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/api/builds': typeof ApiBuildsRouteWithChildren
  '/api/character': typeof ApiCharacterRoute
  '/api/import': typeof ApiImportRoute
  '/api/ninja': typeof ApiNinjaRoute
  '/api/og': typeof ApiOgRoute
  '/api/trade': typeof ApiTradeRoute
  '/build/$id': typeof BuildIdRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builds/leaderboard': typeof ApiBuildsLeaderboardRoute
  '/api/builds/shared': typeof ApiBuildsSharedRoute
  '/api/builds/$id/share': typeof ApiBuildsIdShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/api/builds': typeof ApiBuildsRouteWithChildren
  '/api/character': typeof ApiCharacterRoute
  '/api/import': typeof ApiImportRoute
  '/api/ninja': typeof ApiNinjaRoute
  '/api/og': typeof ApiOgRoute
  '/api/trade': typeof ApiTradeRoute
  '/build/$id': typeof BuildIdRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builds/leaderboard': typeof ApiBuildsLeaderboardRoute
  '/api/builds/shared': typeof ApiBuildsSharedRoute
  '/api/builds/$id/share': typeof ApiBuildsIdShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/api/builds': typeof ApiBuildsRouteWithChildren
  '/api/character': typeof ApiCharacterRoute
  '/api/import': typeof ApiImportRoute
  '/api/ninja': typeof ApiNinjaRoute
  '/api/og': typeof ApiOgRoute
  '/api/trade': typeof ApiTradeRoute
  '/build/$id': typeof BuildIdRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builds/leaderboard': typeof ApiBuildsLeaderboardRoute
  '/api/builds/shared': typeof ApiBuildsSharedRoute
  '/api/builds/$id/share': typeof ApiBuildsIdShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/api/builds'
    | '/api/character'
    | '/api/import'
    | '/api/ninja'
    | '/api/og'
    | '/api/trade'
    | '/build/$id'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/api/builds/leaderboard'
    | '/api/builds/shared'
    | '/api/builds/$id/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/api/builds'
    | '/api/character'
    | '/api/import'
    | '/api/ninja'
    | '/api/og'
    | '/api/trade'
    | '/build/$id'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/api/builds/leaderboard'
    | '/api/builds/shared'
    | '/api/builds/$id/share'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/api/builds'
    | '/api/character'
    | '/api/import'
    | '/api/ninja'
    | '/api/og'
    | '/api/trade'
    | '/build/$id'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/auth/$'
    | '/api/builds/leaderboard'
    | '/api/builds/shared'
    | '/api/builds/$id/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  ApiBuildsRoute: typeof ApiBuildsRouteWithChildren
  ApiCharacterRoute: typeof ApiCharacterRoute
  ApiImportRoute: typeof ApiImportRoute
  ApiNinjaRoute: typeof ApiNinjaRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiTradeRoute: typeof ApiTradeRoute
  BuildIdRoute: typeof BuildIdRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builds': {
      id: '/api/builds'
      path: '/api/builds'
      fullPath: '/api/builds'
      preLoaderRoute: typeof ApiBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/character': {
      id: '/api/character'
      path: '/api/character'
      fullPath: '/api/character'
      preLoaderRoute: typeof ApiCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ninja': {
      id: '/api/ninja'
      path: '/api/ninja'
      fullPath: '/api/ninja'
      preLoaderRoute: typeof ApiNinjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trade': {
      id: '/api/trade'
      path: '/api/trade'
      fullPath: '/api/trade'
      preLoaderRoute: typeof ApiTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/$id': {
      id: '/build/$id'
      path: '/build/$id'
      fullPath: '/build/$id'
      preLoaderRoute: typeof BuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builds/leaderboard': {
      id: '/api/builds/leaderboard'
      path: '/leaderboard'
      fullPath: '/api/builds/leaderboard'
      preLoaderRoute: typeof ApiBuildsLeaderboardRouteImport
      parentRoute: typeof ApiBuildsRoute
    }
    '/api/builds/shared': {
      id: '/api/builds/shared'
      path: '/shared'
      fullPath: '/api/builds/shared'
      preLoaderRoute: typeof ApiBuildsSharedRouteImport
      parentRoute: typeof ApiBuildsRoute
    }
    '/api/builds/$id/share': {
      id: '/api/builds/$id/share'
      path: '/$id/share'
      fullPath: '/api/builds/$id/share'
      preLoaderRoute: typeof ApiBuildsIdShareRouteImport
      parentRoute: typeof ApiBuildsRoute
    }
  }
}

interface ApiBuildsRouteChildren {
  ApiBuildsLeaderboardRoute: typeof ApiBuildsLeaderboardRoute
  ApiBuildsSharedRoute: typeof ApiBuildsSharedRoute
  ApiBuildsIdShareRoute: typeof ApiBuildsIdShareRoute
}

const ApiBuildsRouteChildren: ApiBuildsRouteChildren = {
  ApiBuildsLeaderboardRoute: ApiBuildsLeaderboardRoute,
  ApiBuildsSharedRoute: ApiBuildsSharedRoute,
  ApiBuildsIdShareRoute: ApiBuildsIdShareRoute,
}

const ApiBuildsRouteWithChildren = ApiBuildsRoute._addFileChildren(
  ApiBuildsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  ApiBuildsRoute: ApiBuildsRouteWithChildren,
  ApiCharacterRoute: ApiCharacterRoute,
  ApiImportRoute: ApiImportRoute,
  ApiNinjaRoute: ApiNinjaRoute,
  ApiOgRoute: ApiOgRoute,
  ApiTradeRoute: ApiTradeRoute,
  BuildIdRoute: BuildIdRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
