export const STAT_EXPLANATIONS: Record<string, string> = {
  "Skill DPS": "Damage per second of your main skill",
  "Total EHP": "Effective Hit Pool - total raw damage you can take before dying",
  "Crit Chance": "Chance for attacks/spells to critically strike",
  "Crit Multi": "Damage multiplier when you critically strike",
  "Hit Chance": "Chance to hit the enemy (accuracy vs evasion)",
  "Attack Speed": "Attacks or casts per second",
  "Armour": "Reduces physical damage taken from hits",
  "Evasion": "Rating that determines chance to avoid attack hits",
  "Evade": "Your effective evade chance against same-level enemies",
  "Life Regen/s": "Life regenerated per second",
  "Mana Reserved": "Percentage of mana reserved by auras and heralds",
  "Atk Block": "Chance to block attack damage with shield",
  "Spell Block": "Chance to block spell damage",
  "Suppression": "Spell suppression halves spell damage taken",
  "Phys Reduction": "Percentage of physical damage prevented by armour",
  "Ward": "Absorbs a fixed amount of damage, then goes on cooldown",
  "Str": "Strength - increases melee physical damage and life",
  "Dex": "Dexterity - increases accuracy and evasion",
  "Int": "Intelligence - increases maximum mana and energy shield",
};
